Imbalanced dataset is handled using 2 ways:
  1. Up Sampling
  2. Down Sampling

In [2]:
import numpy as np 
import pandas as pd

In [3]:
# Random seed
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [4]:
n_class_0, n_class_1

(900, 100)

In [9]:
# Create DataFrame with Imbalanced Dataset
class_0 = pd.DataFrame({
  'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
  'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
  'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
  'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
  'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
  'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [10]:
df.head()

   feature_1  feature_2  target
0  -2.639568   0.301225       0
1  -0.199810  -0.064949       0
2  -0.322697  -0.606403       0
3   1.526228  -0.228661       0
4  -1.428047   1.776112       0

In [11]:
df.tail()

     feature_1  feature_2  target
995   3.021088   2.580448       1
996   2.720608   1.469891       1
997   4.699146   1.293526       1
998   2.837299   2.171269       1
999   2.999490   4.052562       1

In [12]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [13]:
# Up sampling
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [14]:
from sklearn.utils import resample 
df_minority_upsampled = resample(
  df_minority, replace=True, 
  n_samples = len(df_majority),
  random_state=42
  )

In [16]:
df_minority_upsampled.shape

(900, 3)

In [17]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.452008   1.905153       1
992   3.033902   0.670199       1
914   2.982557   1.796213       1
971   2.467287   1.652855       1
960   3.192740   1.819643       1

In [18]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [19]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

Down Sampling

In [20]:
import numpy as np 
import pandas as pd

# Random seed
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [22]:
 # Create DataFrame with Imbalanced Dataset
class_0 = pd.DataFrame({
  'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
  'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
  'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
  'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
  'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
  'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [23]:
# Up sampling
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [24]:
from sklearn.utils import resample 
df_majority_downsampled = resample(
  df_majority, replace=False, 
  n_samples = len(df_minority),
  random_state=42
  )

In [25]:
df_majority_downsampled.shape

(100, 3)

In [28]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [29]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64

Down Sampling is bad because we lose too much of data.

-------------------- END ----------------------